spring:
    application:
        name: aurthor
    datasource:
        url: jdbc:postgresql://localhost:5000/aurthorDb
        username: darthchild
        password: changeinprod
    jpa:
        defer-datasource-initialization: true
        properties:
            hibernate.jdbc.time_zone: Asia/Kolkata
            hibernate:
#                show_sql: true
#                format_sql: true
        hibernate:
            ddl-auto: create-drop
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql
logging:
    level:
        com.darthchild.aurthor: DEBUG
        org.hibernate.orm.connections.pooling: warn